### ISSUE TITLE
Multiparty not receiving empty array field

### ISSUE THREAD

**Issue by jmliz** [pillarjs/multiparty#179] opened 2017-07-27 11:04 UTC
Since I'm not sure if the problem is with multiparty I created a SO q to avoid cloning issues:

https://stackoverflow.com/questions/45334719/getting-empty-fields-object-with-express-multiparty-ng-file-upload

Problem is I'm not getting the key with the empty array with the fields. I'm sending:

`{"data": []}`

but multiparty receives an empty object. now, I need the application to know it's receiving an empty array for model manipulation.

**Comment by dougwilson** [comment] 2017-07-27 15:24
Hi @jmliz that is weird indeed. I'm not familiar with Angular, so really have no idea where to start for setting up your upload code to see what is going on here. Can you provide a reproduction case with the steps I need to take to run it?

**Comment by dougwilson** [comment] 2017-10-19 16:50
Closing since I never heard back.

**Closed by dougwilson** 2017-10-19 16:50 UTC
Labels: awaiting more info
