### ISSUE TITLE
data from `part` event causes socket hang up error

### ISSUE THREAD

**Issue by AmBeta** [pillarjs/multiparty#172] opened 2017-04-06 10:35 UTC
The following code didn't work as expected when I tried to make file upload proxy on a node server:

```js
await new Promise((resolve, reject) => {
    const form = new multiparty.Form();
    const formData = new FormData();
    
    // compose `formData` from `part` event
    form.on('part', part => {
        const fieldName = part.name;
        if (part.filename) {
            formData.append(fieldName, part, {
                filename: part.filename,
                contentType: part.headers['content-type'],
                knownLength: part.byteCount
            });
        } else {
            formData.append(fieldName, part);
        }
        part.resume();

        part.on('error', err => {
            part.resume();
        });
    });

    form.on('close', () => {
        const options = {
            method: 'POST',
            body: formData
        };

        // forward to another server
        fetch(`${FoodFileServer}${url}`, options).then(response => {
            if (response.status >= 200 && response.status < 300) {
                resolve(response.body);
            } else {
                reject(response.body);
            }
        }).catch(error => reject(error));
    });

    form.on('error', (error) => {
        reject(error);
    });

    form.parse(request);
});
```

The socket always got hung up when fetching from the remote server.  
But things worked when I composed the `formData` from `field` and `file` events like this:

```js
// compose `formData` from `file` and `field` events
form.on('file', (name, file) => {
    formData.append(name, fs.createReadStream(file.path));
});

form.on('field', (name, value) => {
    formData.append(name, value);
});
```

**Comment by dougwilson** [comment] 2017-04-12 01:47
Hi @AmBeta trying to run your example in Node.js 6.10 is giving me `ReferenceError: FormData is not defined`. Can you provide the following?

1. The version of Node.js you are using
2. The version of this module you are using
3. Complete code I can just copy and paste and run that resolves all dependencies
4. Instructions for how to make the request to reproduce the issue

Thanks!

**Comment by AmBeta** [comment] 2017-04-12 13:35
1. Node version: 6.9.1
2. Modules:  `multiparty`(v4.1.3)  [`form-data`](https://github.com/form-data/form-data)(v2.1.2), and my app runs in `koa`(v2.0.0)

This issue occurs especially when I try to send a request with a file and a string field.

**Comment by dougwilson** [comment] 2017-04-13 02:10
Hi @AmBeta thanks for that information! I still cannot figure out how to get your code in the original post created and what exactly I need to do to make the offending request. Can you provide the following?

1. Complete code I can just copy and paste and run that resolves all dependencies
2. Instructions for how to make the request to reproduce the issue

Thanks!

**Comment by dougwilson** [comment] 2017-05-11 02:26
I'm going to close this since I never heard anything further.

**Closed by dougwilson** 2017-05-11 02:26 UTC
Labels: awaiting more info
