### ISSUE TITLE
form.on('close' event get fired before all form.on('part' are done. NodeJS 14

### ISSUE THREAD

**Issue by hborda** [pillarjs/multiparty#229] opened 2020-06-11 20:53 UTC
I need to move the files that came on a multipart post.  I'm using the form.on('close' to do that.  I have a test running 1000 post, randomly the write fails because I move the file to soon.

I'm using pipes and createWriteStrem to persist the file

Error: ENOENT: no such file or directory, open '/Users/hugoborda/process_data/downloading/1591901856454/1591901856461.json'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:759:7)
    at WriteStream.emit (events.js:210:5)
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23)

**Comment by dougwilson** [comment] 2020-06-11 21:04
Thanks for the report. There is currently an incompatibility with Node.js 14 (https://github.com/pillarjs/multiparty/issues/226) and we will have a fix published soon.

Duplicate of #226

**Closed by dougwilson** 2020-06-11 21:04 UTC

**Comment by hborda** [comment] 2020-06-11 21:10
Is there any way to “subscribe my name somewhere” and get notified when the fix is in place?

Regards

**Comment by dougwilson** [comment] 2020-06-11 21:14
Yes, there arw two methods:

1. I directed as a duplicate of that other issue so you can click the subscribe button on that issue to get a notification on updates, including it being closed (indicating a fix was made).
2. You can go to the main repo page at clikc on watch at the top right and choose "releases only" to be notified when new releases are made.

I hope that helps!
