### ISSUE TITLE
Throw error: stream ended unexpectedly

### ISSUE THREAD

**Issue by nicolelovecoding** [pillarjs/multiparty#184] opened 2017-11-08 19:46 UTC
I have an app running on Cloud Foundry using module multiparty. When I upload files to the app, multiparty has no problem processing files.
But when we deploy the app to kubernetes. This module throwing errors. 
```
2017-11-03T19:25:27.023Z abacus-express 46 Middleware error { message: 'stream ended unexpectedly', status: 400 } - Error: stream ended unexpectedly
    at Form.<anonymous> (/usr/src/app/node_modules/multiparty/index.js:681:24)
    at emitNone (events.js:72:20)
    at Form.emit (events.js:166:7)
    at finishMaybe (/usr/src/app/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/src/app/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at Form.Writable.end (/usr/src/app/node_modules/multiparty/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at onend (_stream_readable.js:498:10)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickDomainCallback (node.js:459:13)
```

**Comment by dougwilson** [comment] 2017-11-09 03:11
Hi @nicolelovecoding that error is because the underlying TCP socket was closed prior to getting a complete multipart form. I'm not sure why that would happen off hand, unfortunately. Can you provide instructions for how I can reproduce the issue and / or a packet capture of the request from the container the Node.js code is running in?

**Comment by dougwilson** [comment] 2017-12-20 18:31
Closing since I never heard back.

**Closed by dougwilson** 2017-12-20 18:31 UTC
Labels: awaiting more info
