### ISSUE TITLE
unexpected endFlush

### ISSUE THREAD

**Issue by clivend** [pillarjs/multiparty#142] opened 2016-08-03 14:41 UTC
Hello everyone and thanks for the good work. I am trying to use multiparty in hapi to upload a file and turn it tu azure, but I get this. Funny part, everything seems to work fine... but I just can't look at that error, and something may be actually wrong.

```
Error: unexpected endFlush
    at endFlush (PATH/node_modules/multiparty/index.js:553:22)
    at PassThrough.<anonymous> (PATH/node_modules/multiparty/index.js:720:5)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

```js
handler: function(request, reply) {

  let form = new multiparty.Form({
    autoFiles: false
  });
  let uniqueFileName = uuid.v1();
  let imagePosition;

  console.log('1');
  form.on('part', function(part) {
    part.on('error', function(err) {
      console.log('5');
    });
    console.log('2');
    if (part.filename !== undefined) {
      console.log(part);
      let extension = part.filename.split('.').pop();
      let size = part.byteCount - part.byteOffset;
      let name = uniqueFileName + '.' + extension;
      console.log('3');

      blobService.createBlockBlobFromStream('mitouser-profile-pictures', name, part, size, function(error) {
        if (error) {
          console.log('4');
        }
        mitoProfilePictureModel
          .create({
            userId: request.auth.credentials.context.mitoUserId,
            name: name,
            position: imagePosition
          })
          .then((newMitoProfilePicture) => {
            if (!newMitoProfilePicture) {
              return Promise.reject(Boom.badRequest("Cannot save picture for user id: " + request.auth.credentials.context.mitoUserId));
            }

            return reply({
              message: 'Ok.'
            });
          })
          .catch((err) => {
            if (err.isBoom) {
              return reply(err);
            } else {
              return reply(Boom.badRequest('Something went wrong while saving picture for user id: ' + err));
            }
          });
      });
    }
    /*
    if (part.name === 'position') {
      //console.log(part);
    }
    */

    part.on('error', function(err) {
      console.log('5');
    });

  });

  form.on('field', function(name, val){
    if(name === 'position'){
      imagePosition = parseInt(val);
    }
  });

  form.on('close', function() {
    console.log('7');
  });

  form.on('error', function(error) {
    console.log('8', error);
  });

  form.on('aborted', function() {
    console.log('9');
  });

  form.parse(request.payload);
}
```
Thanks!

**Comment by dougwilson** [comment] 2017-03-27 04:49
Hi @clivend I'm not sure what is happening, as that error only occurs when something is really mixed up. I can certainly take a look, but would need to get something in hand to debug through. Could you provide all the following?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. A complete server that I can startup and run to reproduce the issue (rather than a code snippet). If you're using other modules, please note down their exact versions as well.
4. Complete instructions for how to run your server code and how to make the offending request to the server.

Thank you!

**Comment by kulkarnih** [comment] 2017-10-12 11:26
Hi.

I'm hitting this issue too. I'm trying to upload a pdf file to Azure. This happens when I upload the file from Chrome {Version 61.0.3163.100 (Official Build) (64-bit)}.

I added some debugs in multiparty/index.js. I've uploaded the index file in this gist.
https://gist.github.com/kulkarnih/abbbc72081c5da4ecee4c1ef33d88be2
I added a debug in beginFlush and endFlush, the value of self.flushing is displayed after it is incremented/decremented.
I added a debug before calling every beginFlush and endFlush. You can search for console.log and you will find all of them.

This is the debug output for chrome. https://gist.github.com/kulkarnih/28ce87073ab0422628df11b40b722375

Request headers
https://gist.github.com/kulkarnih/ffd5a0c799d037e46ac28893965e625b

Request payload
https://gist.github.com/kulkarnih/e28e1daa0459219101c70d3cce3451ab

You can see the name of the file that I'm uploading in the request payload. The file name is 82 characters long. Weirdly, if I decrease it to 62 it is working fine.

node version - v6.7.0
multiparty - 4.1.3
azure - 1.2.0 (This does not matter, because the code is not reaching the library.)

**Comment by kulkarnih** [comment] 2017-10-12 13:36
@clivend `let size = part.byteCount - part.byteOffset;`

This may not give you the correct file size. That might result in Azure emitting the 'end' signal at the wrong time.

Make the client send the file size as a field and use that.

**Comment by dougwilson** [comment] 2017-10-19 16:49
I'm going to close this since I've never heard back from OP. I can always re-open and do want to fix, but I don't know what the issue is, which is why I was seeking further information.

**Closed by dougwilson** 2017-10-19 16:49 UTC
Labels: awaiting more info

**Comment by kulkarnih** [comment] 2017-10-19 17:03
@dougwilson I found that `part.byteCount - part.byteOffset` sometimes gave the wrong file size. If we pass this size to the Azure library, it tries to read the stream beyond the file size. That results in an unexpected endFlush.

I found this issue mainly with pdf files.

**Comment by dougwilson** [comment] 2017-10-19 17:04
Great! Is that a line in this module that needs to be changed?

**Comment by kulkarnih** [comment] 2017-10-19 18:19
@dougwilson No. If you look at @clivend's example code, it is right after the part.filename not undefined check. IMO, either the values given by part.byteCount and/or part.byteOffset are incorrect, or the file size shouldn't be calculated using those. I'm not sure which layer loads those values.

**Comment by dougwilson** [comment] 2017-10-19 18:24
Gotcha.I'm not 100% on exactly what those mean, never really used them and were here before I started working on it :) I can certainly take a look to see what can be done: either fix them or add something new for your use-case. Can you provide the information in https://github.com/pillarjs/multiparty/issues/142#issuecomment-289353273 so I can start to take a look into this?

**Comment by kulkarnih** [comment] 2017-10-23 07:20
1. Node - 6.7.0
2. Azure - 1.2.0-preview, multiparty - 4.1.3
3. There are two files.
    a. main.js - https://gist.github.com/kulkarnih/b83d24aad0f47ab89ff26507db5af1e4
    b. package.json - https://gist.github.com/kulkarnih/737effe760b74c606e703ee36dd6b588
4.
    a. Save main.js and package.json to a directory.
    b. Install dependencies using "npm install ."
    c. Run the server "node main.js"
    d. Use Chrome's Advanced Rest Client or Postman to send a multipart/form-data request to 
        '/upload'.

I could not get the 'endFlush' exception to occur, but the file size calculated using this code https://gist.github.com/kulkarnih/b83d24aad0f47ab89ff26507db5af1e4#file-main-js-L53 is definitely incorrect. I used a pdf file. File size calculated < actual file size. By changing the length of file name we get different sizes for the file. I think the exception happens when calculated file size > actual file size.

**Comment by maciejcichowski** [comment] 2017-11-03 11:35
I found that ` let size = part.byteCount;` instead of` let size = part.byteCount - part.byteOffset;` works great for PDF files.

**Comment by kulkarnih** [comment] 2017-11-04 01:08
@maciejcichowski It sometimes works even with `part.byteCount - part.byteOffset`. But ideally we should get the correct file size.
