### ISSUE TITLE
Multiple duplicate records inserted into the database

### ISSUE THREAD

**Issue by ChenyaZhang** [pillarjs/multiparty#149] opened 2016-09-02 17:42 UTC
When I try to push inside the `form.on('file')` only one time, there are always multiple duplicate records inserted into the database at the same time. Very serious problem. 

```
// on routes that end in /users/competitorAnalysisPhotoData
// ----------------------------------------------------
router.route('/users/competitorAnalysisPhotoData/:userName')

// update the user info (accessed at PUT http://localhost:8080/api/users/competitorAnalysisPhotoData)
    .post(function(req, res) {

    // use our user model to find the user we want
    User.findOne({ userName: req.params.userName}, function(err, user) {

        if (err)
            res.send(err);
        // Got the user name
        var userName = user.userName;
        // parse a file upload
        var form = new multiparty.Form();

        // Errors may be emitted
        // Note that if you are listening to 'part' events, the same error may be
        // emitted from the `form` and the `part`.
        form.on('error', function(err) {
            console.log('Error parsing form: ' + err.stack);
        });

        form.on('file', function(err, files) {
            // Upload photo to the embedded document
            // user.competitorAnalysisPhoto.push({
            //     photo2: files.path
            // });
            if (files.originalFilename === 'photo1.png') {
                if (user.competitorAnalysisPhoto.photo1 == null) {
                    console.log('Photo1 is null!');
                    user.competitorAnalysisPhoto.push({
                        photo1: files.path
                    });
                } else {
                    console.log('Photo1 is not null!');
                    user.update(
                        {
                            userName: userName
                        },
                        { $set: { "competitorAnalysisPhoto.photo1" : files.path } }
                    );
                }

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo2.png') {
                if (user.competitorAnalysisPhoto.photo2 == null) {
                    user.competitorAnalysisPhoto.push({
                        photo2: files.path
                    });
                } else {
                    user.update(
                        {
                            userName: userName
                        },
                        { $set: { "competitorAnalysisPhoto.photo2" : files.path } }
                    );
                }

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo3.png') {
                if (user.competitorAnalysisPhoto.photo3 == null) {
                    user.competitorAnalysisPhoto.push({
                        photo3: files.path
                    });
                } else {
                    user.update(
                        {
                            userName: userName
                        },
                        { $set: { "competitorAnalysisPhoto.photo3" : files.path } }
                    );
                }

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo4.png') {
                if (user.competitorAnalysisPhoto.photo4 == null) {
                    user.competitorAnalysisPhoto.push({
                        photo4: files.path
                    });
                } else {
                    user.update(
                        {
                            userName: userName
                        },
                        { $set: { "competitorAnalysisPhoto.photo4" : files.path } }
                    );
                }

                // save the user
                user.save();
            }
        });

        // form.parse(req);
        form.parse(req);

        // check for error
        if (err)
            return res.send(err);
        return res.json({ message: 'User updated!' });

    });
})`
```

**Comment by dougwilson** [comment] 2017-01-21 18:21
That does sound bad, but I don't see anything obviously wrong with what you posted above, so I'm not sure what to say. Can you provide more information on how we can reproduce the issue?

**Comment by dougwilson** [comment] 2017-03-19 17:55
Hi @ChenyaZhang I'm going to close this issue since I never heard back.

**Closed by dougwilson** 2017-03-19 17:55 UTC
Labels: awaiting more info
