### ISSUE TITLE
Error when using form.parse: 

### ISSUE THREAD

**Issue by somsky** [pillarjs/multiparty#185] opened 2017-11-22 21:02 UTC
Hi,

I'm developing a node app using Hapi as core framework and I want to implement file upload right now. The files are transmitted from my front end as multiparty/form data and are supposed to be parsed by the multiparty framework. My problem is that I can't get the server to parse the form without getting the following error:

**Error: Unknown event end at Object.exports.assert** (/home/somsky/code/webdev/rider/server/node_modules/hoek/lib/index.js:736:11) at internals.Podium.on.internals.Podium.addListener (/home/somsky/code/webdev/rider/server/node_modules/podium/lib/index.js:322:10) at Form.parse (/home/somsky/code/webdev/rider/server/node_modules/multiparty/index.js:137:7)I am using the standard example from the multiparty npm page.

code: 

```
exports.setAvatar = {
  auth: false,

  payload: {
    output: 'stream',
    parse: true,
    allow: 'multipart/form-data'
  },

  handler: function (request, reply) {
    //const user = request.payload;

    var count = 0;
    var form = new multiparty.Form();
     
    // Errors may be emitted 
    // Note that if you are listening to 'part' events, the same error may be 
    // emitted from the `form` and the `part`. 
    form.on('error', function(err) {
      console.log('Error parsing form: ' + err.stack);
    });
     
    // Parts are emitted when parsing the form 
    form.on('part', function(part) {
      // You *must* act on the part by reading it 
      // NOTE: if you want to ignore it, just call "part.resume()" 
     
      if (!part.filename) {
        // filename is not defined when this is a field and not a file 
        console.log('got field named ' + part.name);
        // ignore field's content 
        part.resume();
      }
     
      if (part.filename) {
        // filename is defined when this is a file 
        count++;
        console.log('got file named ' + part.name);
        // ignore file's content here 
        part.resume();
      }
     
      part.on('error', function(err) {
        // decide what to do 
      });
    });
     
    // Close emitted after form parsed 
    form.on('close', function() {
      console.log('Upload completed!');
      res.setHeader('text/plain');
      res.end('Received ' + count + ' files');
    });
     
    // Parse req 
    form.parse(request);

  },
```

Node version: 6.12.0
Node-Framework: Hapi
OS: Ubuntu 16.04 xenial

**Comment by dougwilson** [comment] 2017-11-22 21:57
Hi @somsky I can take a look, but not super familiar with Hapi (only used it a few times) so not sure off-hand what the issue is. Can you provide the following for me to run your code:

1. Complete code I can copy and paste and run and it will actually start up a server. Running that code doesn't actually start a server it seems and I'm not familiar enough with Hapi to understand how to make that code into a running server.
2. The exact request to make to the server once it's running. A `curl` command or if you can include a HTML form and the file to add with instructions would help a lot.
3. The version of Hapi, this module, and any other module you're full example uses.

Thanks!

**Comment by dougwilson** [comment] 2017-12-20 18:31
Closing since I never heard back.

**Closed by dougwilson** 2017-12-20 18:31 UTC
Labels: awaiting more info
