### ISSUE TITLE
Readme example uses "close" instead of "finish"

### ISSUE THREAD

**Issue by GenesysGershy** [pillarjs/multiparty#245] opened 2022-02-03 22:38 UTC
Hello, in my usage (`node: 14.0.0`, `multiparty: 4.2.2`) I cannot detect the successful completion of a multipart request using the `close` event, even though the readme suggests this is possible (under the comment `// Close emitted after form parsed`).

This doesn't work:
```
let form = Form(...);
form.on('close', () => console.log('Success!'));
form.parse(req);
```

Substituting `'finish'` for `'close'` gets this working. Should the readme be updated to reflect this? Thanks!

**Comment by dougwilson** [comment] 2022-02-03 22:46
Hello, sorry you sre having trouble. The readme is correct, as close it what this module specifically emits. You can also check out our test suite. If the close is not being emitted, please provide the details so we can take a look in to this issue: version of this module, version of Node.js, a complete app to run (just use the readme example if that reproduces it) and exactly what the request is that is being sent to the serve. Thank you!

https://github.com/pillarjs/multiparty/blob/fb1806da470bfc61759c4662fb83e110a960754a/index.js#L612

**Comment by dougwilson** [comment] 2022-02-03 22:48
Oh, sorry, you included the versions above, so no need to include them again.

**Comment by dougwilson** [comment] 2022-02-03 23:00
FWIW I just tried with 14.0.0 and version 4.2.2 of this module using the example in the readme and didn't have any issue; the `close` event fired as normal.

One though I had it that your example does not show any event handlers for the file/field/part. If you have a large part and don't handle it, it will put backpressure on the form, and the parsing won't be closed (but of course the stream underlying will be finished). Does adding this to your example cause the close event to be emitted? `form.on('part', (p) => p.resume()) // discard parts`

I can provide that clarity in the docs on the `close` event.

**Comment by dougwilson** [comment] 2022-02-03 23:07
I also just realized, there is no reason why if there is no part handling added to the form that this module can't just discard all the parts. That would make your three line example work. Of course, you'd get no useful data from the form, since you didn't actually do anything with the parts, but it is probably the least surprising thing to do when there is no part handlers.

**Closed** 2022-02-04 01:50 UTC
Labels: awaiting more info
