### ISSUE TITLE
s3 upload is not working

### ISSUE THREAD

**Issue by lazyhoneyant** [pillarjs/multiparty#141] opened 2016-07-18 12:20 UTC
I'm trying to implement s3 upload via multiparty.
but It doesn't work.

There are two problems depend on byteCount variable.

If I set the ContentLenght:part.byteCount, s3 file upload is not working.

but then,

If I omit ContentLength:part.byteCount, s3 file upload is working. 
BUT The only part(chunk of stream?) of entire file have been uploaded. 
e.g) source file size : 100kb, uploaded file size: 20kb

My code is below.
Is there any problems on my code?

```js
  var form = new multiparty.Form();

  form.on('field',function(name,value){    

  });  

  form.on('close',function(){    
    res.json({success:true});
  });  

  form.on('part',function(part){

    if(!part.filename) {
      part.resume();
    } 

    s3 = new AWS.S3();
    var params = {Bucket: s3bucket, Key: tempFileName, Body: part, ContentLength:part.byteCount};

    s3.upload(params, function(err, data) {                      
      console.log('s3 upload');     
    });       


    part.on('data',function(chunk){
      console.log(part.filename+' read '+chunk.length + 'bytes');
    });


    part.on('end',function(){      
      console.log(part.filename+' Part read complete');      
    }); 

  }); 

  form.on('progress',function(byteRead,byteExpected){
       console.log(' Reading total  '+byteRead+'/'+byteExpected);
  });  

  form.on('error', function(err) {
    console.log('err');
  });

  form.parse(req);
```

**Comment by dougwilson** [comment] 2016-08-31 22:04
I have never used that AWS library, so really don't know. Any hints on what the issue is would be very helpful!

**Comment by mikaelfs** [comment] 2016-09-24 02:19
I also had the same problem when implementing S3 upload based on the sample code. After perusing the library and doing some experiments, here is my finding:

1. S3 upload with file method works properly.

Trade-off: a temporary file is created in the disk and should be removed after uploading to S3

Sample code:
`
    var s3Client = new AWS.S3({
        signatureVersion: 'v4'
    });

    var form = new multiparty.Form();    

    form.parse(req, function (err, fields, files) {

        var myFile = files.file[0];
                
        s3Client.upload({
            Bucket: 'BUCKET',
            Key: 'KEY',
            ACL: 'ACL',
            Body: fs.createReadStream(myFile.path)
        }, function (err, data) {
            if (err) {
                //handle error
            } else {
                //handle upload complete

                //delete the temp file
                fs.unlink(myFile.path);                
            }
        });
    });
`

2. S3 upload without callback works by creating a temporary buffer to handle the data

Trade-off: memory exhaustion when the attachment size is big

`
    var s3Client = new AWS.S3({
        signatureVersion: 'v4'
    });

    var form = new multiparty.Form();

    form.on('part', function (part) {         
        if (!part.filename) { //not uploading file
            part.resume();
        }

        if (part.filename) { //a file upload

            //handle upload to Amazon S3            
            var buffer = new Buffer(part.byteCount);
            var bufferOffset = 0;
            part.on('data', function (chunk) {
                //fill the buffer
                buffer.fill(chunk);
                bufferOffset += chunk.length;
            });

            part.on('end', function () {
                //upload to Amazon S3
                s3Client.putObject({
                    Bucket: 'BUCKET',
                    Key: 'KEY',
                    ACL: 'ACL',
                    Body: buffer,
                    ContentLength: part.byteCount
                }, function (err, data) {
                    if (err) {
                        //handle error
                    } else {
                        //handle upload complete
                    }
                });
            });
        }
    });

    form.on('error', function (err) {
        //handle other error
    });

    form.parse(req);
`

**Comment by arasmussen** [comment] 2017-07-20 16:25
@mikaelfs you aren't using `bufferOffset` anywhere and if there are multiple chunks then `buffer.fill` will overwrite rather than appending.

**Comment by echox** [comment] 2017-07-31 14:39
I have also problems getting the right ByteCount...

Upload with just one file works.
Upload with one file and one field gets my wrong ByteCount numbers...

Image size: `240839`
How I upload:
`curl -XPOST -F 'image=@file.png' -F 'test=123' http://localhost:3000/store`

What I get as ByteCount/ByteOffset for the image:
```
Offset: 165 
Count: 240935
```
To get to the correct image size, you need to subtract 96 bytes?
I would have expected `size = byteCount - offset`.

What I get as ByteCount/ByteOffset for the field:
```
Offset: 241097
Count: 3
```

**Comment by dougwilson** [comment] 2017-07-31 14:48
I'm going to close this issue, because back in 2016 I asked what could be wrong with the AWS example since I'm not familiar so it could be fixed and nothing has been offered up. If there is something wrong with the example, please let me know what it is, or even make a pull request (even if that is to remove the example because it is broken).

**Closed by dougwilson** 2017-07-31 14:48 UTC
Labels: examples
