### ISSUE TITLE
Duplicate records inserted in database

### ISSUE THREAD

**Issue by ChenyaZhang** [pillarjs/multiparty#148] opened 2016-09-01 16:18 UTC
The server side seems normal with correct debug messages printing out in the right amount. However, in my database (using Mongodb), there are always duplicate records appear every time in a seemingly random manner.

Node.js server:
```
// on routes that end in /users/competitorAnalysisPhotoData
// ----------------------------------------------------
router.route('/users/competitorAnalysisPhotoData/:userName')

// update the user info (accessed at PUT http://localhost:8080/api/users/competitorAnalysisPhotoData)
    .post(function(req, res) {

    // use our user model to find the user we want
    User.findOne({ userName: req.params.userName}, function(err, user) {

        if (err)
            res.send(err);
        console.log('Got the user in "Put" competitorAnalysisPhotoData!');

        // parse a file upload
        var form = new multiparty.Form();
        // var originalFileName = "";
        // var path = "";

        console.log('This is called 1!');

        // Errors may be emitted
        // Note that if you are listening to 'part' events, the same error may be
        // emitted from the `form` and the `part`.
        form.on('error', function(err) {
            console.log('Error parsing form: ' + err.stack);
        });

        form.on('file', function(err, files) {
            console.log('files: ', files);
            console.log('!!!Original File name: ', files.originalFilename);
            console.log('!!!Path: ', files.path);
            // originalFileName = files.originalFilename;
            // path = files.path;

            // Upload photo to the embedded document
            if (files.originalFilename === 'photo1.png') {
                user.competitorAnalysisPhoto.push({
                    photo1: files.path
                });
                console.log('Got photo1!');

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo2.png') {
                user.competitorAnalysisPhoto.push({
                    photo2: files.path
                });
                console.log('Got photo2!');

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo3.png') {
                user.competitorAnalysisPhoto.push({
                    photo3: files.path
                });
                console.log('Got photo3!');

                // save the user
                user.save();
            } else if (files.originalFilename === 'photo4.png') {
                user.competitorAnalysisPhoto.push({
                    photo4: files.path
                });
                console.log('Got photo4!');

                // save the user
                user.save();
            }
        });

        // form.parse(req);
        form.parse(req);

        // check for error
        if (err)
            return res.send(err);
        return res.json({ message: 'User updated!' });

    });
})`
```

Is there anything wrong with the way I save the user?
Or is it due to some cache data in 'user' when I try to push a new one?

**Comment by dougwilson** [comment] 2017-01-21 18:22
Duplicate of #149

**Closed by dougwilson** 2017-01-21 18:22 UTC
